language: node_js

node_js:
    - 'lts/*'

# https://stackoverflow.com/a/52387639
cache:
    directories:
        - '$HOME/.npm'

stages:
    - check
    - test

jobs:
    include:
        - stage: check
          script: npm run tsc
          name: 'Typecheck'
        - script: npm run lint
          name: 'Linter'
        - stage: test
          script: npm run test:update
          name: 'Unit Test'
